AllCops:
  Exclude:
    - db/schema.rb
    - tmp/**/*
    - vendor/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
    - Gemfile.lock
    - Rakefile
  TargetRubyVersion: 2.6.5

# Missing magic comment # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: false

# Missing top-level class documentation comment
Style/Documentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/LineLength:
  IgnoredPatterns:
    - "^"
    - "#"
    - "!"
  Exclude:
    - "db/seeds.rb"
